function [sys, x, y, z, y_mrna, z_mrna ] = createIncoherentFFL( ...
    RNAP ...
    , Ribo ...
    , k_txn ...
    , k_tln ...
    , x_deg ...
    , x_init ...
    , y_deg ...
    , y_init ...
    , z_deg ...
    , z_init ...
    , y_rna_deg ...
    , y_ribo_on ...
    , y_ribo_off ...
    , y_rna_init ...
    , z_rna_deg ...
    , z_ribo_on ...
    , z_ribo_off ...
    , z_rna_init ...
    , y_rnap_on ...
    , y_rnap_off ...
    , y_bindX ...
    , y_unbindX ...
    , y_copy_number ...
    , z_rnap_on ...
    , z_rnap_off ...
    , z_bindX ...
    , z_unbindX ...
    , z_bindY ...
    , z_unbindY ...
    , zy_bindX ...
    , zy_unbindX ...
    , zx_bindY ...
    , zx_unbindY ...
    , z_copy_number ...
    , x_coop ...
    , y_coop ...
    )

sys = SimpleResourceBioSystem( RNAP, Ribo, k_txn, k_tln );
%addProtein( name, degredation rate, initial value )
x = sys.addProtein( 'X', x_deg, x_init );
y = sys.addProtein( 'Y', y_deg, y_init);
z = sys.addProtein( 'Z', z_deg, z_init);
%addmRNA( name, protein, degredation rate, ribo on rate, ribo off rate, initial value )
y_mrna = sys.addmRNA( 'mRNA_Y', y, y_rna_deg, y_ribo_on, y_ribo_off, y_rna_init );
z_mrna = sys.addmRNA( 'mRNA_Z', z, z_rna_deg, z_ribo_on, z_ribo_off, z_rna_init );
%addGene( name, mRNA, promoterStates, rnapOn, rnapOff, transitionMatrix, copy# )
x_binding = repmat( x, 1, x_coop );
y_binding = repmat( y, 1, y_coop );
xy_binding = [x_binding, y_binding];
y_gene = sys.addGene( 'Gene_Y', y_mrna, { [], x_binding }, [ 0, y_rnap_on ], [ 0, y_rnap_off ], [ 0 , y_bindX^x_coop ; y_unbindX^x_coop, 0 ] , y_copy_number );
z_states = { [], x_binding, y_binding, xy_binding };
%edge detector ffl
z_on = [ 0, z_rnap_on, 0, 0 ];
z_off = [ 0, z_rnap_off, 0, 0 ];
z_trans = [ 0 , z_bindX^x_coop, z_bindY^y_coop, 0 ; ...
    z_unbindX^x_coop , 0, 0, zx_bindY^y_coop ; ...
    z_unbindY^y_coop, 0, 0, zy_bindX^x_coop ; ...
    0, zx_unbindY^y_coop, zy_unbindX^x_coop, 0 ];
z_gene = sys.addGene( 'Gene_Z', z_mrna, z_states, z_on, z_off, z_trans, z_copy_number );




end